//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _422_Baranov_Shoes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderItems = new HashSet<OrderItems>();
        }
    
        public int ProductID { get; set; }
        public string ArticleNumber { get; set; }
        public int ProductNameID { get; set; }
        public int UnitID { get; set; }
        public decimal Price { get; set; }
        public int SupplierID { get; set; }
        public int ManufacturerID { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> CurrentDiscount { get; set; }
        public int StockQuantity { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItems> OrderItems { get; set; }
        public virtual ProductNames ProductNames { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        public virtual Units Units { get; set; }
    }
}
